tunnel: 0464f391-dcc3-4073-b775-a9caa040edf1
credentials-file: /etc/cloudflared/markhachem.json

ingress:
  - hostname: www.markhachem.com
    service: http://cms:3000
    originRequest:
      httpHostHeader: cms:3000
      noTLSVerify: true
  - hostname: markhachem.com
    service: http://cms:3000
    originRequest:
      httpHostHeader: cms:3000
      noTLSVerify: true
  - service: http_status:404
