/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    artists: Artist;
    exhibitions: Exhibition;
    news: News;
    events: Event;
    fairs: Fair;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    exhibitions: ExhibitionsSelect<false> | ExhibitionsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    fairs: FairsSelect<false> | FairsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    homepage: Homepage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for images. Not required for PDFs or documents.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  /**
   * URL slug. Auto-generated from name if left blank.
   */
  slug?: string | null;
  category: 'modern' | 'contemporary';
  /**
   * Surface on the homepage roster.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  nationality?: string | null;
  /**
   * e.g. "Lebanese, 1924–2006". Overrides auto-formatted nationality/years.
   */
  displayMeta?: string | null;
  birthYear?: number | null;
  deathYear?: number | null;
  /**
   * Hero image shown on the artist page (portrait or signature artwork).
   */
  portrait?: (number | null) | Media;
  /**
   * e.g. "Taureau, 2015"
   */
  portraitTitle?: string | null;
  /**
   * e.g. "Bronze, edition of 8 — 50 × 70 cm"
   */
  portraitMedium?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Curriculum Vitae — education, solo shows, group shows, collections, awards. Use headings + bullet lists. Shown as its own section on the artist page.
   */
  cv?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  additionalArtworks?:
    | {
        image: number | Media;
        /**
         * e.g. "Couleur additive, Série 14, 2018".
         */
        title?: string | null;
        /**
         * e.g. "Ceramic — 80 × 80 cm".
         */
        medium?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Items about the artist — interviews, reviews, video features, catalogues. Renders as a labelled list of external links.
   */
  publications?:
    | {
        /**
         * e.g. "Interview — Le Monde, Mar 2024".
         */
        label: string;
        type?: ('article' | 'video' | 'interview' | 'catalogue' | 'review' | 'other') | null;
        /**
         * Full URL including https://.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Artist's own external presence — personal website, Instagram, Artnet profile, gallery profiles elsewhere.
   */
  links?:
    | {
        /**
         * e.g. "Instagram", "Artnet profile".
         */
        label: string;
        /**
         * Full URL including https://.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Square-ish artwork image used on the home card (often a "-sml" variant of the artist-page portrait).
   */
  featuredArtwork?: (number | null) | Media;
  /**
   * Caption title, e.g. "Couleur additive, Série 14".
   */
  featuredArtworkTitle?: string | null;
  /**
   * Caption medium, e.g. "Ceramic — 80 × 80 cm".
   */
  featuredArtworkMedium?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions".
 */
export interface Exhibition {
  id: number;
  title: string;
  /**
   * URL slug. Auto-generated from title if left blank.
   */
  slug?: string | null;
  city: 'paris' | 'new-york' | 'beirut' | 'other';
  /**
   * Pin to the homepage "Now Showing" block.
   */
  isNowShowing?: boolean | null;
  featured?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Free-form date string as it should appear on the site (e.g. "08 - 25 January, 2025" or "du 10 avril au 1er Mai 2025"). Overrides formatted start/end.
   */
  displayDates?: string | null;
  /**
   * Address or venue line, e.g. "28 Place des Vosges, 75003".
   */
  location?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Render the cover with `is-artwork` styling (contained, padded, light background) when the source is an artwork rather than a photo.
   */
  coverIsArtwork?: boolean | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  artists?: (number | Artist)[] | null;
  /**
   * Upload a PDF (preferred for new exhibitions).
   */
  pdf?: (number | null) | Media;
  /**
   * External PDF URL (used for legacy archive.org links).
   */
  pdfExternalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL slug. Auto-generated from title if left blank.
   */
  slug?: string | null;
  /**
   * Surface in the homepage News block.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  publishedDate?: string | null;
  subtitle?: string | null;
  /**
   * Display string, e.g. "7 March — 12 July 2026".
   */
  dateRange?: string | null;
  /**
   * City, e.g. "Tourcoing".
   */
  location?: string | null;
  /**
   * e.g. "Retrospective", "Biennale".
   */
  badgeLabel?: string | null;
  badgeStyle?: ('default' | 'gold') | null;
  coverImage?: (number | null) | Media;
  /**
   * Venue line including curator (rendered above the excerpt).
   */
  venue?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short summary shown on the homepage card.
   */
  excerpt?: string | null;
  /**
   * Full article body for the detail page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Important events in galleries, museums, and artist studios — talks, openings, studio visits, fairs, screenings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL slug. Auto-generated from title if left blank.
   */
  slug?: string | null;
  /**
   * Surface in the homepage Events block.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  publishedDate?: string | null;
  subtitle?: string | null;
  /**
   * Display string, e.g. "7 March — 12 July 2026".
   */
  dateRange?: string | null;
  /**
   * City, e.g. "Paris".
   */
  location?: string | null;
  /**
   * e.g. "Gallery", "Museum", "Studio Visit".
   */
  badgeLabel?: string | null;
  badgeStyle?: ('default' | 'gold') | null;
  coverImage?: (number | null) | Media;
  /**
   * Venue line including host or curator (rendered above the excerpt).
   */
  venue?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short summary shown on the homepage card.
   */
  excerpt?: string | null;
  /**
   * Full event description for the detail page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairs".
 */
export interface Fair {
  id: number;
  name: string;
  /**
   * URL slug. Auto-generated from name if left blank.
   */
  slug?: string | null;
  status: 'upcoming' | 'current' | 'past';
  /**
   * Surface on the homepage "Current & Upcoming" rich-card section.
   */
  showInLatest?: boolean | null;
  /**
   * Show in the homepage "Art Fairs" logo grid.
   */
  showInFairsGrid?: boolean | null;
  /**
   * Lower numbers appear first in the grid.
   */
  sortOrder?: number | null;
  /**
   * Square logo for the §11 grid.
   */
  logo?: (number | null) | Media;
  /**
   * Photo for the §10 rich card (Current & Upcoming).
   */
  coverImage?: (number | null) | Media;
  /**
   * e.g. "Basel"
   */
  city?: string | null;
  /**
   * Section §11 line, e.g. "Basel & New York".
   */
  location?: string | null;
  /**
   * Short description shown in the §11 grid card.
   */
  description?: string | null;
  /**
   * Footer line for the §11 card, e.g. "Booth C01" / "Recurring Participant" / "2024 Participant".
   */
  participationLine?: string | null;
  booth?: string | null;
  /**
   * Display string, e.g. "14–17 May 2026".
   */
  dateRange?: string | null;
  venue?: string | null;
  /**
   * Used to sort the §10 cards.
   */
  startDate?: string | null;
  /**
   * Sub-rows on the §10 card, e.g. VIP Preview / Public Days.
   */
  dateRows?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'exhibitions';
        value: number | Exhibition;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'fairs';
        value: number | Fair;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  featured?: T;
  sortOrder?: T;
  nationality?: T;
  displayMeta?: T;
  birthYear?: T;
  deathYear?: T;
  portrait?: T;
  portraitTitle?: T;
  portraitMedium?: T;
  bio?: T;
  cv?: T;
  additionalArtworks?:
    | T
    | {
        image?: T;
        title?: T;
        medium?: T;
        id?: T;
      };
  publications?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  featuredArtwork?: T;
  featuredArtworkTitle?: T;
  featuredArtworkMedium?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions_select".
 */
export interface ExhibitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  city?: T;
  isNowShowing?: T;
  featured?: T;
  startDate?: T;
  endDate?: T;
  displayDates?: T;
  location?: T;
  coverImage?: T;
  coverIsArtwork?: T;
  description?: T;
  artists?: T;
  pdf?: T;
  pdfExternalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  publishedDate?: T;
  subtitle?: T;
  dateRange?: T;
  location?: T;
  badgeLabel?: T;
  badgeStyle?: T;
  coverImage?: T;
  venue?: T;
  excerpt?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  publishedDate?: T;
  subtitle?: T;
  dateRange?: T;
  location?: T;
  badgeLabel?: T;
  badgeStyle?: T;
  coverImage?: T;
  venue?: T;
  excerpt?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairs_select".
 */
export interface FairsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  showInLatest?: T;
  showInFairsGrid?: T;
  sortOrder?: T;
  logo?: T;
  coverImage?: T;
  city?: T;
  location?: T;
  description?: T;
  participationLine?: T;
  booth?: T;
  dateRange?: T;
  venue?: T;
  startDate?: T;
  dateRows?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  galleryName?: string | null;
  tagline?: string | null;
  foundedYear?: number | null;
  foundedCity?: string | null;
  /**
   * In international format, e.g. "+33 6 09 18 27 11".
   */
  whatsappNumber?: string | null;
  /**
   * Pre-filled into the WhatsApp chat when a visitor taps the floating button.
   */
  whatsappPrefilledMessage?: string | null;
  navigation?: {
    /**
     * Top nav menu items, in order.
     */
    links?:
      | {
          label: string;
          /**
           * Internal path or full URL.
           */
          href: string;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Photos in the homepage horizontal strip. Order matters; the strip duplicates the set for the seamless loop.
   */
  galleryStrip?:
    | {
        image: number | Media;
        /**
         * Falls back to the media alt if blank.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  locations?:
    | {
        city: string;
        isPrimary?: boolean | null;
        /**
         * A location can have multiple addresses (Paris has two).
         */
        addresses?:
          | {
              /**
               * One line per row.
               */
              lines: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional. Used when there is no concrete address (e.g. NYC: "By appointment only").
         */
        presenceText?: string | null;
        phones?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        email?: string | null;
        hours?: string | null;
        /**
         * Google Maps share link.
         */
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  socials?: {
    instagram?: string | null;
    facebook?: string | null;
    artsy?: string | null;
    artnet?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroImage?: (number | null) | Media;
  heroImageMobile?: (number | null) | Media;
  kicker?: string | null;
  /**
   * The bold first line of the title.
   */
  titleStrong?: string | null;
  /**
   * The second line of the title.
   */
  titleRest?: string | null;
  /**
   * Dot-separated tagline phrases under the title.
   */
  taglinePillars?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Founder portrait.
   */
  portrait?: (number | null) | Media;
  quote?: string | null;
  attribution?: string | null;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  milestones?:
    | {
        /**
         * e.g. "1996" or "300+".
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Order matters — drag to reorder. Drives the homepage roster.
   */
  featuredArtists?: (number | Artist)[] | null;
  /**
   * Order matters. Cards on the homepage News block.
   */
  featuredNews?: (number | News)[] | null;
  /**
   * Order matters. Cards on the homepage Past Exhibitions block.
   */
  featuredPastExhibitions?: (number | Exhibition)[] | null;
  /**
   * Each card links to the artist page.
   */
  featuredCollectionWorks?:
    | {
        artist: number | Artist;
        image?: (number | null) | Media;
        /**
         * Work title or location/dates.
         */
        title?: string | null;
        medium?: string | null;
        id?: string | null;
      }[]
    | null;
  contactCta?: {
    heading?: string | null;
    subheading?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  galleryName?: T;
  tagline?: T;
  foundedYear?: T;
  foundedCity?: T;
  whatsappNumber?: T;
  whatsappPrefilledMessage?: T;
  navigation?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
              id?: T;
            };
      };
  galleryStrip?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  locations?:
    | T
    | {
        city?: T;
        isPrimary?: T;
        addresses?:
          | T
          | {
              lines?: T;
              id?: T;
            };
        presenceText?: T;
        phones?:
          | T
          | {
              value?: T;
              id?: T;
            };
        email?: T;
        hours?: T;
        mapUrl?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        artsy?: T;
        artnet?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroImage?: T;
  heroImageMobile?: T;
  kicker?: T;
  titleStrong?: T;
  titleRest?: T;
  taglinePillars?:
    | T
    | {
        text?: T;
        id?: T;
      };
  portrait?: T;
  quote?: T;
  attribution?: T;
  heading?: T;
  body?: T;
  milestones?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  featuredArtists?: T;
  featuredNews?: T;
  featuredPastExhibitions?: T;
  featuredCollectionWorks?:
    | T
    | {
        artist?: T;
        image?: T;
        title?: T;
        medium?: T;
        id?: T;
      };
  contactCta?:
    | T
    | {
        heading?: T;
        subheading?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}